# Generated by CloudInfra Designer
# 2025-10-23T21:11:01.094Z

resource "aws_vpc" "main_vpc" {
  cidr_block = "10.0.0.0/16"
  enable_dns_hostnames = true
  enable_dns_support   = true
  tags = {
    Name = "main_vpc"
    Environment = var.environment
    lvc_id = "vpc_main"
  }
}

resource "aws_subnet" "public_subnet_a" {
  vpc_id     = aws_vpc.main_vpc.id
  cidr_block = "10.0.0.0/16"
  availability_zone = "us-east-1a"
  tags = {
    Name = "public_subnet_a"
    Environment = var.environment
    lvc_id = "subnet_public_a"
  }
}

resource "aws_subnet" "private_subnet_a" {
  vpc_id     = aws_vpc.main_vpc.id
  cidr_block = "10.0.0.0/16"
  availability_zone = "us-east-1a"
  tags = {
    Name = "private_subnet_a"
    Environment = var.environment
    lvc_id = "subnet_private_a"
  }
}

resource "aws_instance" "web_server" {
  instance_type = "t3.micro"
  ami           = "ami-0c55b159cbfafe1f0"
  subnet_id     = aws_subnet.public_subnet_a.id
  tags = {
    Name = "web_server"
    Environment = var.environment
    lvc_id = "ec2_web"
  }
}

resource "aws_instance" "app_server" {
  instance_type = "t3.small"
  ami           = "ami-0c55b159cbfafe1f0"
  subnet_id     = aws_subnet.private_subnet_a.id
  tags = {
    Name = "app_server"
    Environment = var.environment
    lvc_id = "ec2_app"
  }
}


# === Infrastructure Relationships (Generated from Diagram Edges) ===
